### ISSUE TITLE
bug: topicWriter.WaitInitInfo and WithWriterSetAutoSeqNo(false) return -1 as LastSeqNum 

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb-go-sdk#1011]
# Bug Report

**YDB GO SDK version:** 3.55.0

`topicWriter.WaitInitInfo(...)` always return LastSeqNum == -1 if topicwriter starts with option `WithWriterSetAutoSeqNo(false)`

**Comment by size12** [comment]
Hi, do you think that it is really bug? `topicWriter.WaitInitInfo(...)` returns `InitInfo` which contains only `LastSeqNum` field.
This object edits once, when writer initializes. 
<img width="661" alt="image" src="https://github.com/ydb-platform/ydb-go-sdk/assets/54941444/8019b9f8-91d1-47d4-bbd0-bcb374b8c793">
And when `topicWriter.WaitInitInfo(...)` called, writer will always return same object with same values;
Also there is a test, which says that `info` object should be idempotent
<img width="624" alt="image" src="https://github.com/ydb-platform/ydb-go-sdk/assets/54941444/eff065ec-20d9-41cb-8470-014885b8fe2b">

I see solution in writing function as example `GetLastSeqNo`, which will return actual sequence number. What do you think?

**Comment by klenovda** [comment]
In my case I need to deduplicate messages based on their seqNo, and I'm managing its value myself. At the moment, I'm obtaining information either through the WaitInitInfo() method or the deprecated topicoptions.WithOnWriterFirstConnected() method, where the seqNo is consistently -1.

For my use case, it would be beneficial to have methods like GetLastSeqNo() or GetInfo() implemented.
