### ISSUE TITLE
Uuid

### ISSUE THREAD

**Issue by asmyasnikov** [ydb-platform/ydb-go-sdk#1069]
Next code must be worked:
```go
params := ydb.ParamsBuilder().
     Param("$param").Uuid(uuid.New()).Build()
```
Variable `params` can be used in 
```go
err := db.Table().Do(ctx, func(ctx, s) error) {
    res, tx, err := s.Execute(ctx, txControl, `
        -- DECLARE $param AS Uuid;
        SELECT $param;
    `, params)
    . . .
})
```
See [`ydb.Builder().Param("$name").List()`](https://github.com/ydb-platform/ydb-go-sdk/blob/master/internal/params/parameters.go#L105) as example

**Comment by size12** [comment]
i get into this task
