### ISSUE TITLE
Finaliser for pool gc

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb-go-sdk#150]
https://github.com/ydb-platform/ydb-go-sdk/blob/710f840ee7ebe369be75d032299352e5be2199a1/internal/conn/pool.go#L74

I think about counter with implicit close object when counter = 0 is un-intuitive.

What about:
1. Write separate method Close() - for close logic and call it when close needed
2. Use runtime.SetFinalizer - for call implicit Close() if pool doesn't need
3. Add Hook OnClosed - can help determine call in tests [example](https://go.dev/play/p/C-0HHwAbjyI)

**Comment by asmyasnikov** [comment]
all places for release pool are known. No need to use runtime.SetFinalizer
