### ISSUE TITLE
dev: Какая библиотека основная?

### ISSUE THREAD

**Issue by polRk** [ydb-platform/ydb-go-sdk#213]
Существует еще одна библиотека https://github.com/yandex-cloud/ydb-go-sdk. (v2)
Какой лучше пользоваться?

**Comment by asmyasnikov** [comment]
Эта библиотека основная. В репозитории yandex-cloud сделал пометку, что теперь надо использовать этот репозиторий

**Comment by polRk** [comment]
@asmyasnikov Оффтоп: На основе v2 был пример с [cloud functions и ydb](functions https://github.com/yandex-cloud/examples/blob/master/serverless/serverless_voximplant/ydb.go); как лучше всего использовать v3 чтобы уменьшить cold start и переиспользовать подключение к бд?

**Comment by asmyasnikov** [comment]
Как-то по коду я не вижу что используется какой-то шареный драйвер. Функция init() вызывается при импорте пакета. В YF. То есть всегда. Может функция не умирает, у меня нет точного понимания в этом месте. И даже не понимаю как это померить.

В любом случае инициализацию драйвера в init можно сделать легко

**Comment by polRk** [comment]
> В любом случае инициализацию драйвера в init можно сделать легко

Примерно так?
```go
package main

var db ydb.Connection

func init() {
	db, err = ydb.Open(ctx, dsn, environ.WithEnvironCredentials(ctx))

	if err != nil {
		panic(fmt.Errorf("connect error: %w", err))
	}
}

func Handler(ctx context.Context) (string, error) {
  var result string
  err := db.Table().Do(...)

  return result, err
}
```

**Comment by polRk** [comment]
Или так 
```go
func init() {
	ctx, cancel := context.WithCancel(context.Background())

	var err error
	db, err = ydb.Open(context.Background(), dsn, environ.WithEnvironCredentials(ctx))
	if err != nil {
		panic(fmt.Errorf("connect error: %w", err))
	}

	go func() {
		exit := make(chan os.Signal, 1)
		signal.Notify(exit, os.Interrupt, os.Kill, syscall.SIGTERM)

		cancel()
		_ = db.Close(ctx)
	}()
}
```

**Comment by positiveviking** [comment]
`os.Kill` бессмысленно перехватывать.

ну и для того, чтобы по сигналу что-то можно было выполнить надо чтобы в `main()` подождали завершения (в функциях этого вроде не обещают). Т.е. никаких гарантий что что-то закроется.

В остальном - правильно закрывать через  `db.Close(ctx)`

**Comment by polRk** [comment]
Просто примеров нет cf + ydb. Может ваши коллеги смогу дать на мой вопрос: "как правильно использовать ydb с cloud functions на go"?

**Comment by polRk** [comment]
@positiveviking @asmyasnikov  Если открывать соединение на каждый вызов функции, то функция возвращает результат (чтение всей таблицы StreamReadTable с 1 строкой )  за 300 ms (p 75). 
<img width="252" alt="Снимок экрана 2022-04-21 в 15 51 55" src="https://user-images.githubusercontent.com/39828645/164462135-2dc0bb44-ae60-491b-9fa7-e53a2c2ce085.png">

Если открывать соединение в init и переиспользовать подключение, то 60ms (p 75).
<img width="288" alt="Снимок экрана 2022-04-21 в 15 51 59" src="https://user-images.githubusercontent.com/39828645/164462170-9f1256f0-8246-4ea3-b8e6-28fa83a53ce2.png">

Метрики с YDB - выполнение операции (запрос+ответ) за 5ms. 
Передача данных по цепочке YDB-GO -> YDB -> YDB-GO при переиспользовании занимает 55ms (что, наверное много); при создании подключения 295ms, что неплохо, но хочется лучше

**Comment by polRk** [comment]
Даже YDB работает быстрее при переиспользовании подключения

<img width="125" alt="Снимок экрана 2022-04-21 в 16 09 02" src="https://user-images.githubusercontent.com/39828645/164465011-2766cecb-1e66-45bc-b379-b0eb52787453.png">

> Первых две пики - новое подключение на каждый запрос, последняя - переиспользование

**Comment by asmyasnikov** [comment]
Пара мыслей.

1. Ресурсы надо освобождать, никто не спорит
2. В частности драйвер при закрытии "тушит" серверные акторы.
3. Акторы ydb достаточно легковесны
4. Акторы, которые забыли закрыть, будут закрыты по idle
5. Если в функции 1-2 вызова, то драйвер  создает 1+ акторов

Вывод: кажется можно не закрывать драйвер пока решение с закрытием контейнера функции не найдено

**Comment by positiveviking** [comment]
> @positiveviking А есть возможность связаться напрямую с командой и попросить поддержать ydb более "нативно"?

У облака есть форма предложений фичей, чат в телеграм и поддержка.
Этот репозиторий не относится к продукту
