### ISSUE TITLE
dev: replace usage internal/lazy package with sync.Once in connection

### ISSUE THREAD

**Issue by asmyasnikov** [ydb-platform/ydb-go-sdk#218]

**Comment by asmyasnikov** [comment]
Will not to be done

Lazy package helps to create sub-clients and improves all sub-client call with retry.
May be `lazy` name is not true, but true name has not found

**Comment by positiveviking** [comment]
>but on Close call of uninitiated client may be race
Make `once.Do(func(){})` and it will not initialize anymore.

**Comment by asmyasnikov** [comment]
Ok, lets assume next case:
- first goroutine with lazy init with sync.Once call
```
once.Do(func(){
  client := builder.New
})
```
- second goroutine with call Close()
```
if client == nil { // race when client pointer is defining now
  // forgot closing if client initialized after check with nil
  return 
}
// legal closing
```

**Comment by asmyasnikov** [comment]
Code improvement in this issue have no explicit profit, but have some bugs in corner cases

**Comment by asmyasnikov** [comment]
Ok, single once for init and for close internal client - nice idea
