### ISSUE TITLE
Wrong time.Duration to Interval conversion

### ISSUE THREAD

**Issue by WhiteBars** [ydb-platform/ydb-go-sdk#241]
https://github.com/ydb-platform/ydb-go-sdk/blob/afc2b4337964777a4cae96c419cbf571d8281249/table/types/value.go#L63

There is problem with time conversion. In Golang time has nanoseconds accuracy while YDB Interval has microsecond accuracy. So time duration after conversion multiplying by 100 and time became incorrect

**Comment by asmyasnikov** [comment]
https://ydb.tech/en/docs/yql/reference/types/primitive#datetime

**Comment by WhiteBars** [comment]
There is a code represents the problem I found
https://pastebin.com/7BN6j7Mx

10 microsecond not equal 10 microseconds.

**Comment by asmyasnikov** [comment]
fixed
