### ISSUE TITLE
feat: add getter to Value struct

### ISSUE THREAD

**Issue by alexeyco** [ydb-platform/ydb-go-sdk#277]
# Feature Request

**Describe the Feature Request**

Please, [see suggested diff](https://github.com/ydb-platform/ydb-go-sdk/pull/275) to understand my idea  

**Related Code**

[In my query builder](https://github.com/alexeyco/ydbx/blob/feature-new-way/builder/buffer.go#L54) I want to generate declare-queries automatically. What do I mean (keep reading).

```go
yql, params, err := builder.New("select * from my_table where id = ?", types.StringValueFromString("id"))
```

But there is no possibilities to get a Type from Value.

**Comment by polRk** [comment]
@alexeyco It may be interested https://github.com/ydb-platform/ydb-go-sdk/pull/281
