### ISSUE TITLE
Есть возможность сделать вывод много строчных ошибок без \n ?

### ISSUE THREAD

**Issue by polRk** [ydb-platform/ydb-go-sdk#293]
https://github.com/ydb-platform/ydb-go-sdk/blob/2bb3c7b8a3c71849de91343a871319855eae1e2b/internal/xerrors/transport.go#L77

https://cloud.yandex.ru/docs/functions/lang/golang/logging
Многострочные сообщения должны быть разделены символом \r (carriage return), но не \n (line feed). При использовании последнего каждая строка отправляется отдельным сообщением и отображается в журнале отдельно.

**Comment by asmyasnikov** [comment]
fixed
