### ISSUE TITLE
Add something like 'CompareOptionsDiff'

### ISSUE THREAD

**Issue by shmel1k** [ydb-platform/ydb-go-sdk#406]
# Feature Request

**Describe the Feature Request**

Problem that I have: I am writing terraform provider for YDB and Topics as a part. In tests I want to check if I created Alter request correctly. Currently I have some callbacks that will be called in future but I can not test what is really going on inside.

**Describe Preferred Solution**

Add something like 
```go
CompareOptionsDiff(expectedOptions []AlterOption, actual []AlterOption) (diff string, equal bool)  {...}
```
which will return equality of options and diff if something differs. It can be stored in `testutil` package or somewhere else.

**Describe Alternatives**

To be discussed!

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by rekby** [comment]
I suggest to place the function to testutil package
