### ISSUE TITLE
feat: YDB support in squirrel

### ISSUE THREAD

**Issue by asmyasnikov** [ydb-platform/ydb-go-sdk#443]
PR with YDB support to https://github.com/Masterminds/squirrel (SQL query builder)

**Comment by flymedllva** [comment]
hi, I followed the fork path, since the library is rarely updated and it seems you can just fork it and expand it with your own functions

see what happened, maybe there will be ideas for improvement
https://github.com/flymedllva/ydb-go-qb

**Comment by Loganche** [comment]
Hey, @flymedllva 
Thank you for your ideas, in June I've added some features for SELECT, DROP and CREATE. You can check the [pr](https://github.com/Masterminds/squirrel/pull/370) or go to forked [repo](https://github.com/ydb-platform/squirrel/tree/master) with this features in master.

Also thanks for your query builder, I'll grab some ideas :)

**Comment by Loganche** [comment]
@asmyasnikov maybe we can close this issue or update the status in here
