### ISSUE TITLE
feat: do not execute request to database for committed transactions

### ISSUE THREAD

**Issue by misty-fungus** [ydb-platform/ydb-go-sdk#48]
# Feature Request

**Describe the Feature Request**

Consider typical transactions usage:

```go
func foo(ctx context.Context, s table.Session) error {
    txControl := table.TxControl(table.BeginTx(table.WithSerializableReadWrite()))
    tx, res, err := s.Execute(ctx, txControl, "SELECT ... ", ...)
    // ...
    defer tx.Rollback(ctx)
    _, err = tx.Execute(ctx, "UPDATE ...", ...)
    _, err = tx.CommitTx(ctx, ...)
    return err
}
```

In case of `CommitTx()` success  result of `tx.Rollback()` is known **before** the call

It seems, that current implementaion still executes a request to YDB
```
tskv    unixtime=1636635598.026496      levelname=WARN  name=ydb.driver.core    caller=trace/driver_gtrace.go:729       message=invoke failed   version=3.3.3   latency=1.665293ms      address=<address> dataCenter=true method=/Ydb.Table.V1.TableService/RollbackTransaction   error=ydb: operation error: NOT_FOUND: [{#2015 Transaction not found: fe709ffb-4afe6090-274c38cd-e2b585da}]
```

Since it's quite common practice to execute rollback unconditionally in `defer` we can skip extra call to database and return well-known result.

Another snippet from ((https://github.com/golang/go/blob/master/src/database/sql/sql.go#L2303-L2306 database/sql))

```go
func (tx *Tx) rollback(discardConn bool) error {
	if !atomic.CompareAndSwapInt32(&tx.done, 0, 1) {
		return ErrTxDone
	}
```

**Describe Preferred Solution**

Add atomic value to track transaction end of life (committed or rollbacked)

**Describe Alternatives**

leave as is

**Additional Context**

* https://stackoverflow.com/questions/46421602/why-defer-a-rollback
* https://golang.org/doc/database/execute-transactions#example

**Comment by asmyasnikov** [comment]
Fixed https://github.com/ydb-platform/ydb-go-sdk/commit/43ec07ead31f633360a1335509e0bcc3bfecff35
