### ISSUE TITLE
bug: Topic reader stop receive events after a hour of work.

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb-go-sdk#487]
# Bug Report

**YDB GO SDK version:** v3.40.1

**Comment by positiveviking** [comment]
Period of time is strongly correlated with [CredUpdateInterval](https://github.com/ydb-platform/ydb-go-sdk/blob/master/internal/topic/topicreaderinternal/stream_reader_impl.go#L78)

**Comment by rekby** [comment]
Is is reproduced, the bug seen as server bug.
Wait check/fix by server team.

**Comment by rekby** [comment]
Workaround: set infinite time for update token: [WithReaderUpdateTokenInterval](https://pkg.go.dev/github.com/ydb-platform/ydb-go-sdk/v3@v3.41.0/topic/topicoptions#WithReaderUpdateTokenInterval)
