### ISSUE TITLE
bug: retry all errors, but unretriable for topic service

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb-go-sdk#488]
# Bug Report

**YDB GO SDK version:** 3.41.0

**Current behavior:** retry only retriable error.

**Expected behavior:**
retry all error, but unretriable (retry error without explicit known abotu retriable/non retriable).

**Comment by positiveviking** [comment]
NOTE: This issue is about topics.

Here should be implemented some kind of method to define additional error classes to retry connections.
I.e. user shoud be able to define if auth errors should be fatal for reader/writer

**Comment by rekby** [comment]
error text in the case:

```
ydb: writer is closed: ydb: failed to receive message from write stream: ydb: failed to read grpc message from writer stream: operationStatus error: GENERIC_ERROR: [{#500100 pipe to partition's tablet is dead}]
```

It is like to server bug: server return unretriable status for retriable error.
