### ISSUE TITLE
feat: add leader election API into coordination client

### ISSUE THREAD

**Issue by asmyasnikov** [ydb-platform/ydb-go-sdk#53]
`Алексей Мясников, [11 Jan 2022, 18:35:31]:`
А расскажи кейс зачем это надо? 
Я распросил про плюсовый клиент - там сложно как для пользователя, так и реализация
Как бы вопроизвести смогу, но с точки зрения пользовательского АПИ точно сверхсложно. Как просто сделать - думаю пока.
Точнее даже так: надо выдумать простое пользовательское АПИ. Я бы предложил что-то типа
```
db.Coordination().Lock("some_resource", count) // спим пока не залочимся
// делаем что надо
db.Coordination().Unlock("some_resource", count)
```
Ибо тема с сессиями асинхронными запросами-ответами - такое себе

`Yaroslav Leonov, [11 Jan 2022, 22:12:13]:`
слушай, ну тема стандартная. Есть некий процесс, который должен быть синглтоном в глобальном смысле. Примеры: 
1) запуск задачи по крону в YT/sandbox
2) контроллер, управляющий pod_set в YP (например, реагирующий на запросы выселения подов с хостов)
По соображениям redundancy при выпадении ДЦ процесс должен остаться живым. т.е. надо где-то взять глобальную блокировку. Кто лок взял, тот и leader.
В моём случае задача такая: пользователь приходит и создаёт таск сендбокса/тасклетов. Это простая запись в БД. Фактический запуск асинхронный, т.е. где-то должен быть тред, который перекладывает из YDB в запущенный yt|sandbox операции.
Вот эта штука должна быть в одном экземпляре
Тут есть прямо тонкость-тонкость если процесс, как в моём случае, работает с YDB и берёт блокировку в YDB. Тут может быть неприятность, когда блокировку он взял, но по каким-то причинам (была всего 1 сессия и она исчерпалась блокировкой), а с YDB работать больше не может
Но на это можно не сильно закладываться, в реальности такое будет редко
Типично для этого используют zookeeper
тут есть некоторая проблемка, типа бекенд взял лок в зукипере, но не может достучаться до YDB. Но на это опять можно не закладываться, очень краеугольный случай
для вдохновения можешь вот это почитать:
оригинал на java https://curator.apache.org/curator-recipes/index.html
форк на питоне https://github.com/python-zk/kazoo/tree/master/kazoo/recipe
короче, да-да-да, пример с локом ^^^ закроет 99% проблем
хотя, нет. лок же можно из-за флапов потерять
те нужно какую-то cancel функцию передавать
`Алексей Мясников, [11 Jan 2022, 23:47:31]:`
Да, подумал уже об этом
`Yaroslav Leonov, [11 Jan 2022, 23:36:44]:`
все же в etcd кажется красиво сделано. первичный объект там лиза, с которой работаешь, ее и пропагейтить во внешние системы можно
ладно, я увлекся. короче у тебя механика потери лока при флапах сети не описана
https://kazoo.readthedocs.io/en/latest/api/recipe/lock.html
```
zk = KazooClient()
zk.start()
lock = zk.Lock("/lockpath", "my-identifier")
with lock:  # blocks waiting for lock acquisition
    # do something with the lock
```
https://github.com/apache/curator/tree/master/curator-examples
в репку куратора можешь посмотреть, там неплохо с звёздами
`Алексей Мясников, [11 Jan 2022, 22:32:29]:`
`start` кажется лишний. Можно совместить с `lock`
Yaroslav Leonov, [11 Jan 2022, 22:33:41]:
не знаю почему так сделано. у zk очень сложный API и bug prone API
насколько я помню start там асинхронный, т.е. он future возвращает
типа код 
```
f = zk.start()
f.wait()
spawn 100 threads
```
можно поменять на 
```
zk.get('/')
spawn 100 threads
```
если тебе почему-то хочется стартовать треды после коннкета. 
а, ну вот наверное разумный пример:
мне дёрнули GET /stop в API, я хочу приостановить работу. в zk я могу сделать `zk.stop()` и лишние треды попадают. при неявном `start()` в api мне код писать нужно
короче тут скорее дело вкуса
recipe package - go.etcd.io/etcd/client/v3/experimental/recipes - pkg.go.dev
etcd: https://pkg.go.dev/go.etcd.io/etcd/client/v3@v3.5.1/experimental/recipes
но у них есть election session и mutex
https://pkg.go.dev/go.etcd.io/etcd/client/v3@v3.5.1/concurrency

**Comment by asmyasnikov** [comment]
```
// wait for lock
// Returned ctx with cancel, 
// use it for operations under lock
locker, ctx, err := db.Coordination().Lock(
  ctx, 
  "resource", 
  coordination.WithCount(2),
)
If err != nil {
  // wrap err
}
defer locker.Unlock(
  coordination.WitchCount(2),
)
// Doing under lock
```

**Comment by floatdrop** [comment]
Here one use case from the wild. We need to launch migrations in global (in scope of database) lock to eliminate concurrent database modification: https://github.com/golang-migrate/migrate/pull/677#discussion_r774905889

**Comment by rekby** [comment]
как тебе вариант сначала создавать локер (без серверного вызова), а потом блокировки дёргать уже через него?
контекст при возврате тогда точно не нужен, ошибка тут опциональна - тольпо для проверки аргумента ресурса.

```golang
locker := db.Coordination().CreateLocker("resource")
ctx, err := locker.Lock(ctx)
...
locker.Unlock(ctx)


ctx, err := locker.Lock(ctx, WithLockCount(3))
...
locker.Unlock(ctx, WithLockCount(2)) // тут как я понял надо дать возможность частичной разблокировки.
// если разблокировать можно только тот вес, что взял - при анлоке эту опцию просто не допускать.
```

**Comment by asmyasnikov** [comment]
Наверное так можно будет разделить блокировки. Есть ещё нюанс - ресурс надо создавать с одинаковым счётчиком на всех клиентах. Если первый клиент ждёт локер на 10, а второй на 100, то надо возвратить где-то ошибку

**Comment by rekby** [comment]
Если счётчик всегда одинаковый - зачем он вообще нужен? тогда получается это просто shared-lock с ограничением на количество локов и параметр не нужен.
