### ISSUE TITLE
bug: Flaky test TestReadersWritersStress

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb-go-sdk#558]
# Bug Report

**YDB GO SDK version:** 3.42.8

```
--- FAIL: TestReadersWritersStress (0.27s)
    --- FAIL: TestReadersWritersStress//local/stress-topic-9 (70.05s)
        topic_stress_test.go:196: 
```
https://github.com/ydb-platform/ydb-go-sdk/actions/runs/4123815294/jobs/7122295474

https://github.com/ydb-platform/ydb-go-sdk/blob/91de13baf63f65d535709b1ec93477c74f341495/tests/topic_stress_test.go#L196-L196

**Comment by asmyasnikov** [comment]
Repro https://github.com/ydb-platform/ydb-go-sdk/actions/runs/4176680680/jobs/7233290384#step:5:28099

**Comment by rekby** [comment]
reproduced: https://github.com/ydb-platform/ydb-go-sdk/actions/runs/4323527211/jobs/7547236138
