### ISSUE TITLE
bug: compilation error with grpc/resolver @ v1.53.0

### ISSUE THREAD

**Issue by dveselov** [ydb-platform/ydb-go-sdk#567]
Hello, I tried to build a minimal example, but compilation fails with following error:
```
# github.com/ydb-platform/ydb-go-sdk/v3/internal/xresolver
../pkg/mod/github.com/ydb-platform/ydb-go-sdk/v3@v3.42.8/internal/xresolver/xresolver.go:27:3: cannot use c.target.Endpoint (value of type func() string) as type string in argument to trace.DriverOnResolve
```

Looks like grpc@v1.53/resolver Endpoint became a function, so downgrading to v.1.52 is fixing this bug:

```
$ go get google.golang.org/grpc@v1.52.3
go: downloading google.golang.org/grpc v1.52.3
go: downgraded google.golang.org/grpc v1.53.0 => v1.52.3
```

# Bug Report

**YDB GO SDK version:** ydb-go-sdk/v3

**Environment**: macOS Ventura 13.1, go 1.19

**Current behavior:** compilation fails

**Expected behavior:** compilation succeed, example working

**Steps to reproduce:** install ydb-go-sdk, try to compile minimal example

**Related code:** 

**Other information:**

**Comment by asmyasnikov** [comment]
fixed. Wait next release of ydb-go-sdk
