### ISSUE TITLE
dev: SLO workload action every PR

### ISSUE THREAD

**Issue by asmyasnikov** [ydb-platform/ydb-go-sdk#568]
Make as nodejs SDK https://github.com/ydb-platform/slo-nodejs/blob/main/.github/workflows/ci.yml

**Comment by zeruk** [comment]
@asmyasnikov Correct `CI` example now is here: https://github.com/ydb-platform/ydb-nodejs-sdk/blob/main/.github/workflows/slo.yml 
Workload sample and description is here: https://github.com/ydb-platform/ydb-nodejs-sdk/tree/main/slo-workload
As seen from repo, you'll need to create directory for workload package and provide `Dockerfile` inside.
