### ISSUE TITLE
bug: topic writer stops connections retry on GENERIC_ERROR

### ISSUE THREAD

**Issue by positiveviking** [ydb-platform/ydb-go-sdk#649]
# Bug Report

**YDB GO SDK version:**

**Environment**

**Current behavior:**

Writer dead and does not try to reestablish connection

```
failed to read grpc message from writer stream: operationStatus error: GENERIC_ERROR: [{#500100 pipe to partition's tablet is dead}] at `github.com/ydb-platform/ydb-go-sdk/v3/internal/conn.(*grpcClientStream).RecvMsg(grpc_client_stream.go:113)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/grpcwrapper/rawtopic/rawtopicwriter.(*StreamWriter).Recv(streamwriter.go:45)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/topic/topicwriterinternal.(*SingleStreamWriter).receiveMessagesLoop(writer_single_stream.go:179)` at `github.com/ydb-platform/ydb-go-sdk/v3/internal/topic/topicwriterinternal.(*WriterReconnector).Write(writer_reconnector.go:197)`
```

**Expected behavior:**

Errors should be retried

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by rekby** [comment]
It is expected behavior from SDK: GENERIC_ERROR is non retriable error: https://ydb.tech/en/docs/reference/ydb-sdk/error_handling.

But it is not expected from server side - tablet die must raise retriable error.
Server side guys working for fix it in internal ticket LOGBROKER-7989
