### ISSUE TITLE
bug: unable to use topicoptions.WithOnWriterConnectedInfo

### ISSUE THREAD

**Issue by asukhodko** [ydb-platform/ydb-go-sdk#693]
# Bug Report

**YDB GO SDK version:**

v3.43.0

**Current behavior:**

Cannot pass an argument to `topicoptions.WithOnWriterFirstConnected`.
Getting a compile error: "Cannot use 'func(info topicoptions.WithOnWriterConnectedInfo) { }' (type func(info topicoptions.WithOnWriterConnectedInfo)) as the type OnWriterInitResponseCallback"

**Expected behavior:**

code compiled without errors

**Steps to reproduce:**

```go
onceConnected := func(info topicoptions.WithOnWriterConnectedInfo) {
	// ...
}

writer, err := topicClient.StartWriter(topic, ..., topicoptions.WithOnWriterFirstConnected(onceConnected)
```

**Other information:**

Ultimately, it requires the ability to get LastSeqNo before calling `Write`. It might be useful to have an `Init` method that returns `WithOnWriterConnectedInfo` instead of using the `WithOnWriterFirstConnected` option.

**Comment by rekby** [comment]
Hello, @asukhodko try to add return "error" for onceConnected.

```
onceConnected := func(info topicoptions.WithOnWriterConnectedInfo) error {
	// ...
}
```
