### ISSUE TITLE
dev: make closing connections parallel

### ISSUE THREAD

**Issue by gingersamurai** [ydb-platform/ydb-go-sdk#759]
[Here](https://github.com/ydb-platform/ydb-go-sdk/blob/768a3cbda48a9b97d554de8b35f487e13e65a060/internal/conn/pool.go#L142
) connections are closing sequentially, so if a connection hangs and a context timeout occurs, then all next connections will not be able to close.
Possible solution is to use a separate goroutine for each connection closure.
```golang
var issues []error
errorsCh := make(chan error, len(conns))
wg := sync.WaitGroup{}
wg.Add(len(conns))
for _, c := range conns {

	go func(c closer.Closer) {
		defer wg.Done()
		if err := c.Close(ctx); err != nil {
			errorsCh <- err
		}
	}(c)
}
wg.Wait()
close(errorsCh)

for err := range errorsCh {
	issues = append(issues, err)
}
```

**Comment by asmyasnikov** [comment]
Can you make a PR with this fixes?

**Comment by gingersamurai** [comment]
> Can you make a PR with this fixes?

You can check my PR [here](https://github.com/ydb-platform/ydb-go-sdk/pull/768).
